# Generated by Django 5.1.6 on 2025-03-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
