# Generated by Django 5.1.6 on 2025-03-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
